language: node_js
node_js:
  - '6.7'
services:
  - mongodb
cache:
  directories:
    - node_modules
git:
  depth: 3
skip_cleanup: true

before_install:
  - openssl aes-256-cbc -K $encrypted_5598d1100971_key -iv $encrypted_5598d1100971_iv -in EscalatorAPI.pem.enc -out EscalatorAPI.pem -d

before_script:
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm prune
  - chmod +x deploy.sh

script:
  - npm run ci-lint
  - npm test

after_success:
  - ./deploy.sh

after_script:
  - rm -f EscalatorUI.pem
  - npm run report-coverage
